### ISSUE TITLE
Multiple paths are not recogonized

### ISSUE THREAD

**Issue by AugustoDeveloper** [dschuermans/TagBuildOnPathChangesExtension#1]
Hi,

First of all, congrats for this repository, helped me so much!

And sorry for my english, it's a crap.

I just found a issue and i came here to explain what happened:
When i input more than one path, the changes in my git don't identify has some change inside of paths inputed.
This is occurring because the vsts not pass the paths as a array but as a single string.
And verbose mode not working.

I have the code to solve this issue and i can share with you, if you want.

![image](https://user-images.githubusercontent.com/4335700/45697131-7aa68c80-bb3b-11e8-9329-c9769e830b0b.png)
![image](https://user-images.githubusercontent.com/4335700/45697197-9e69d280-bb3b-11e8-9b5e-57af903f9b36.png)

**Comment by dschuermans** [comment]
Hey @AugustoDeveloper 

Have you tried adding /* at the end of your paths?

**PoiTestTools.LoadTestTool/\*,PoiTestTools.TestTool/\***
I'm using multiple paths myself so i'm pretty confident it should work :)

And the reason you're not seeing verbose output (i think) is because you need to set the System.Debug variable to true when queuing your build.

**Comment by AugustoDeveloper** [comment]
Thks for the tip (System.Debug).
But, the process not working...

![image](https://user-images.githubusercontent.com/4335700/45768296-e871b780-bc12-11e8-9dc9-48df29a166a1.png)

Without "*"

![image](https://user-images.githubusercontent.com/4335700/45768400-2078fa80-bc13-11e8-9aed-f8a1113e9744.png)

**Comment by dschuermans** [comment]
And you're sure that the commit for which the build is triggered has changes in that path?On 19 Sep 2018 18:51, Augusto Mesquita <notifications@github.com> wrote:Thks for the tip (System.Debug).
But, not working..

Without "*"

**Comment by AugustoDeveloper** [comment]
Yes, the image demonstrate:

![image](https://user-images.githubusercontent.com/4335700/45772746-f299b300-bc1e-11e8-892e-c19108066cda.png)

It was created a new file in this commit, called delete-me.txt

**Comment by dschuermans** [comment]
@AugustoDeveloper yes, you're right.

Then to be honest i have no idea why it's not working. Could be that VSTS changed something how parameters are passed.
I haven't used VSTS in a while, we are using on premise TFS (which lacks behind in version compared to VSTS)

If you have the fix, feel free to submit a Pull Request and I'll merge it. Otherwise i'll have to investigate myself but I don't have that much time on my hands nowadays.

**Comment by dschuermans** [comment]
@AugustoDeveloper I just did a test on VSTS.
When I add the script itself to my sources and call it using the powershell task, it works as expected:

![image](https://user-images.githubusercontent.com/6634696/45808445-1c59e500-bcc6-11e8-9995-64f589a05454.png)

When I however use the task with the same settings, it does not detect it. So i'm guessing it's how VSTS passes the data to the powershell script.
I'd have to investigate further but for now you could the same thing as I did:

1.) Add a powershell task to your build
2.) Set it to be inline
3.) Add the following to the script block:

```
$VerbosePreference = "continue"
$Tag="test"
$PathFilters=@("PoiTestTools.LoadTestTool","PoiTestTools.TestTool")
$isTagged = $false
$CreateVariable = $true

# Get changes
$changes=$(git diff head head~ --name-only)

foreach($file in $changes){

    if($null -ne ($PathFilters | ? { $file.StartsWith($_) })){
        Write-Verbose "$File matches a filter, tagging build."
        Write-Host "##vso[build.addbuildtag]$Tag"
        $isTagged = $true
        break
    }
    else{
        Write-Verbose "$File - NO MATCH"
    }
}

if($CreateVariable -eq $true){
    Write-Verbose "Creating variable with name $Tag and value $isTagged"
    Write-Host "##vso[task.setvariable variable=$Tag]$isTagged"
}
```

**Comment by dschuermans** [comment]
I'll update when the extension is working correctly again.

**Comment by AugustoDeveloper** [comment]
> @AugustoDeveloper I just did a test on VSTS.
> When I add the script itself to my sources and call it using the powershell task, it works as expected:
> 
> ![image](https://user-images.githubusercontent.com/6634696/45808445-1c59e500-bcc6-11e8-9995-64f589a05454.png)
> 
> When I however use the task with the same settings, it does not detect it. So i'm guessing it's how VSTS passes the data to the powershell script.
> I'd have to investigate further but for now you could the same thing as I did:
> 
> 1.) Add a powershell task to your build
> 2.) Set it to be inline
> 3.) Add the following to the script block:
> 
> ```
> $VerbosePreference = "continue"
> $Tag="test"
> $PathFilters=@("PoiTestTools.LoadTestTool","PoiTestTools.TestTool")
> $isTagged = $false
> $CreateVariable = $true
> 
> # Get changes
> $changes=$(git diff head head~ --name-only)
> 
> foreach($file in $changes){
> 
>     if($null -ne ($PathFilters | ? { $file.StartsWith($_) })){
>         Write-Verbose "$File matches a filter, tagging build."
>         Write-Host "##vso[build.addbuildtag]$Tag"
>         $isTagged = $true
>         break
>     }
>     else{
>         Write-Verbose "$File - NO MATCH"
>     }
> }
> 
> if($CreateVariable -eq $true){
>     Write-Verbose "Creating variable with name $Tag and value $isTagged"
>     Write-Host "##vso[task.setvariable variable=$Tag]$isTagged"
> }
> ```

Yeah, i did this before open this issues and worked well, thanks anyway.
