### ISSUE TITLE
Not working for TFVC

### ISSUE THREAD

**Issue by nickolas-heirbaut** [dschuermans/TagBuildOnPathChangesExtension#2]
I receive the following error when using TFVC. 

![image](https://user-images.githubusercontent.com/11282419/52414778-83493080-2ae5-11e9-86bd-af1623cb6244.png)

**Comment by AJH16** [comment]
This only works for Git.  If you look at what the code is doing, it's running a git command in powershell to get the list of changed files.  It could theoretically be extended to work with TVFS by doing a TVFS pathway, but the code isn't currently there.

**Comment by dschuermans** [comment]
Hi @nickolas-heirbaut,

@AJH16  is correct. This extension was made using Git in TFS.
We don't use TFS anymore so I didn't bother looking into it.

It's open source, feel free to fork and make adjustment in order to support it :)
